const gilhung81 = [
  { value: 0, gilhung: '모름', description: '모름' },
  { value: 1, gilhung: '대길', description: '형통, 복록' },
  { value: 2, gilhung: '대흉', description: '혼란, 혼돈' },
  { value: 3, gilhung: '대길', description: '천혜의 복' },
  { value: 4, gilhung: '대흉', description: '요절, 양화' },
  { value: 5, gilhung: '대길', description: '성공, 복록' },
  { value: 6, gilhung: '대길', description: '은덕, 평안' },
  { value: 7, gilhung: '대길', description: '뜻을 이룸' },
  { value: 8, gilhung: '대길', description: '목적을 이룸' },
  { value: 9, gilhung: '대흉', description: '불행, 파멸' },
  { value: 10, gilhung: '대흉', description: '몰락, 고독' },
  { value: 11, gilhung: '대길', description: '부귀, 영화' },
  { value: 12, gilhung: '대흉', description: '병약, 비극' },
  { value: 13, gilhung: '대길', description: '지모, 책략' },
  { value: 14, gilhung: '대흉', description: '실패, 빈곤' },
  { value: 15, gilhung: '대길', description: '명성, 덕망' },
  { value: 16, gilhung: '대길', description: '부귀, 영예' },
  { value: 17, gilhung: '대길', description: '돌파, 성사' },
  { value: 18, gilhung: '대길', description: '지혜, 용기' },
  { value: 19, gilhung: '대흉', description: '불운, 허망' },
  { value: 20, gilhung: '대흉', description: '파멸, 패망' },
  { value: 21, gilhung: '대길', description: '지도, 대운' },
  { value: 22, gilhung: '대흉', description: '병약, 실패' },
  { value: 23, gilhung: '대길', description: '권세, 권위' },
  { value: 24, gilhung: '대길', description: '지모, 번창' },
  { value: 25, gilhung: '대길', description: '권위, 부귀' },
  { value: 26, gilhung: '길', description: '파란, 영웅' },
  { value: 27, gilhung: '대흉', description: '좌절, 비탄' },
  { value: 28, gilhung: '대흉', description: '조난, 불길' },
  { value: 29, gilhung: '대길', description: '대성, 대길' },
  { value: 30, gilhung: '대흉', description: '고난, 실패' },
  { value: 31, gilhung: '대길', description: '대망, 수령' },
  { value: 32, gilhung: '대길', description: '희망, 대길' },
  { value: 33, gilhung: '대길', description: '전도양양' },
  { value: 34, gilhung: '대흉', description: '환난, 파멸' },
  { value: 35, gilhung: '대길', description: '순리, 대길' },
  { value: 36, gilhung: '대흉', description: '고난, 역경' },
]

export const getGilhung = (value: number) => {
  return gilhung81[value]
}
